name: Setup project
description: Install required tools
inputs:
  java-version:
    description: Desired Java version
    default: "21.0.8"
  node-version:
    required: false
    description: node version to install
    # Use pre-installed Node version in Ubuntu 22.04 runner
    # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
    default: 24.13.0
  windows-fix:
    required: false
    description: https://github.com/actions/setup-node/issues/899#issuecomment-1837381044
    default: "false"
runs:
  using: composite
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}
    - uses: actions/setup-node@v4
      if: ${{ inputs.windows-fix == 'true' }}
      name: (Windows fix) Setup node without cache
      with:
        node-version: ${{ inputs.node-version }}
    - name: Enable corepack
      shell: bash
      run: |
        corepack enable
        yarn --version
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "yarn"
