ws_dir = Pathname.new(__dir__)
ws_dir = ws_dir.parent until
  File.exist?("#{ws_dir}/node_modules/react-native-test-app/macos/test_app.rb") ||
  ws_dir.expand_path.to_s == '/'
require "#{ws_dir}/node_modules/react-native-test-app/macos/test_app.rb"

workspace 'AsyncStorageMacosExample.xcworkspace'

# 1 - enable new arch, 0 - disable it
ENV["RCT_NEW_ARCH_ENABLED"]="1"

use_test_app! :hermes_enabled => true, :fabric_enabled => false
